server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mymovie?useUnicode=true&characterEncoding=utf8
    username: root
    password:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  http:
    encoding:
      force: true
  #dubbo
  dubbo:
    application:
      name: mymovie-rest
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      name: dubbo
      port: 20881
    scan: com.chao.mymovie.rest.service
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.chao.mymovie.rest.model
logging:
  config: classpath:logback-spring.xml
#pagehelper分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
